src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Product name must be at least {{ limit }} characters long",
     *      maxMessage = "Product name cannot be longer than {{ limit }} characters",
     *      allowEmptyString = false
     * )
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @Assert\Range(
     *      min = 0,
     *      notInRangeMessage = "Price must be greater than {min}",
     *     )
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 250,
     *      minMessage = "Product description must be at least {{ limit }} characters long",
     *      maxMessage = "Product name cannot be longer than {{ limit }} characters",
     *      allowEmptyString = false
     * )
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * *@Assert\Range(
     *      min = 0.1,
     *      notInRangeMessage = "Discount must be greater than {min}",
     *     )
     * @ORM\Column(type="integer", nullable=true)
     */
    private $discount;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=Vendor::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vendor;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="product", orphanRemoval=true)
     */
    private $images;

    /**
     * @Assert\All({
     * @Assert\File(
     *     maxSize = "2048k",
     *     mimeTypes = {"image/png"},
     *     mimeTypesMessage = "Please upload a valid Image"
     * ),
     * @Assert\Image(
     *     minWidth = 200,
     *     maxWidth = 4000,
     *     minHeight = 200,
     *     maxHeight = 4000
     * )
     * })
     */
    private $productImages;

    /**
     * @ORM\OneToMany(targetEntity=CartItem::class, mappedBy="product")
     */
    private $cartItems;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="product", orphanRemoval=true)
     */
    private $orderItems;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->cartItems = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    public function setDiscount(?int $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getVendor(): ?Vendor
    {
        return $this->vendor;
    }

    public function setVendor(?Vendor $vendor): self
    {
        $this->vendor = $vendor;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }

    public function getFinalPrice()
    {
        $price = $this->price - $this->price*$this->discount/100;

        return $price;
    }

    function __toString()
    {
        return $this->name;
    }


    /**
     * @return Collection|CartItem[]
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): self
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems[] = $cartItem;
            $cartItem->setProduct($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): self
    {
        if ($this->cartItems->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getProduct() === $this) {
                $cartItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems[] = $orderItem;
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProductImages()
    {
        return $this->productImages;
    }

    /**
     * @param mixed $productImages
     * @return Product
     */
    public function setProductImages($productImages)
    {
        $this->productImages = $productImages;
        return $this;
    }



}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\User;
use App\Entity\Product;
use App\Entity\Vendor;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use App\Repository\VendorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function index(ProductRepository $productRepository,CategoryRepository $categoryRepository, VendorRepository $vendorRepository): Response
    {
        //1.$categories = $this->getDoctrine()->getRepository(Category::class)->findAll();

        //2.$categories = $categoryRepository->findAll();


        return $this->render('default/index.html.twig',
            [
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'productsNewest'=>$productRepository->findBy([],['id'=>'DESC'],4),
                'productsReels'=>$productRepository->findBy(['category'=>2], ['id'=>'DESC'], 4),
                'productsRods'=>$productRepository->findBy(['category'=>8], ['id'=>'DESC'], 4)
            ]);
    }

    /**
     * @Route("/category/{category}", name="category")
     */
    public function category(ProductRepository $productRepository,CategoryRepository $categoryRepository,VendorRepository $vendorRepository, Category $category): Response
    {

        return $this->render('default/category.html.twig',
            [
                'category'=>$category,
                'products'=>$productRepository->findAll(),
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll()

            ]);
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function contact(CategoryRepository $categoryRepository, VendorRepository $vendorRepository, ProductRepository $productRepository): Response
    {
        return $this->render('default/contact.html.twig',
            [
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'products'=>$productRepository->findAll()
            ]);
    }

    /**
     * @Route("/vendor/{vendor}", name="vendor")
     */
    public function vendor(Vendor $vendor, VendorRepository $vendorRepository, CategoryRepository $categoryRepository, ProductRepository $productRepository): Response
    {
        return $this->render('default/vendor.html.twig',
            [   'vendor'=>$vendor,
                'vendors'=>$vendorRepository->findAll(),
                'categories'=> $categoryRepository->findAll(),
                'products'=>$productRepository->findAll()
            ]);
    }

    /**
     * @Route("/discount", name="discount")
     */
    public function discount(ProductRepository $productRepository,CategoryRepository $categoryRepository, VendorRepository $vendorRepository): Response
    {
        return $this->render('default/discount.html.twig',
            [
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'products'=>$productRepository->findBy([],['discount'=>'DESC'],12)
            ]);
    }

    /**
     * @Route("/product/{product}", name="product")
     */
    public function product(Product $product,ProductRepository $productRepository,CategoryRepository $categoryRepository, VendorRepository $vendorRepository): Response
    {
        return $this->render('default/product.html.twig',
            [
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'product'=>$product

            ]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/admin", name="admin")
     */
    public function admin(CategoryRepository $categoryRepository, VendorRepository $vendorRepository, ProductRepository $productRepository): Response
    {
        return $this->render('default/adminPage.html.twig',
            [
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'products'=>$productRepository->findAll()
            ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/user", name="user")
     */
    public function userPannel(User $user, CategoryRepository $categoryRepository, VendorRepository $vendorRepository, ProductRepository $productRepository): Response
    {
        return $this->render('default/userPage.html.twig',
            [
                'user'=>$user,
                'categories'=>$categoryRepository->findAll(),
                'vendors'=>$vendorRepository->findAll(),
                'products'=>$productRepository->findAll()
            ]);
    }
}

templates/default/adminPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin Page{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5 mb-2">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">What you can do</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td><a href="{{ url('category_index') }}">Add/Delete/Edit Category </a></td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <<td><a href="{{ url('crud_product_index') }}">Add/Delete/Edit Product </a></td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td><a href="{{ url('vendor_index') }}">Add/Delete/Edit Vendor </a></td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td><a href="{{ url('crud_user_index') }}">Add/Delete/Edit User </a></td>
                    </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}

templates/default/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12"><h2>Categoria {{ category.name }}</h2></div>

            {% for product in category.getProducts() %}
                {{ include ('default/product/productCard.html.twig') }}
            {% endfor %}

        </div>
    </div>

{% endblock %}

templates/default/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5 mb-2">
                <h2>
                    Detalii de contact
                </h2>
            </div>
            <div class="ml-4 mt-3">
                <div>
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <span class="h5">Adress</span>
                    <div>
                        <a href="https://www.google.com/maps/place/Strada+Bucure%C8%99ti+1,+Cluj-Napoca+400000/@46.7801654,23.5941663,17z/data=!3m1!4b1!4m5!3m4!1s0x47490ea0fe9df953:0x2a11fb18bbf7d46a!8m2!3d46.7801654!4d23.596355" target="_blank">
                            Str. Bucuresti nr.1
                        </a>
                    </div>
                </div>
                <div class="mt-3">
                    <i class="fa fa-mobile" aria-hidden="true"></i>
                    <span class="h5">Number</span>
                    <div>
                        <span>+40123456789</span>
                    </div>
                </div>
                <div class="mt-3">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span class="h5">E-mail</span>
                    <div>
                        <span>yourshop@shop.ro</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/discount.html.twig
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block body %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col-12">
                <div class="container mt-5">
                    <div class="row">
                        <div class="col-12">
                            <h3>Prinde cele mai bune oferte!</h3>
                        </div>
                        {% for product in products %}
                            {{ include ('default/product/productCard.html.twig') }}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block body %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col-12">
                <div class="container mt-5">
                    <div class="row">
                        <div class="col-12">
                            <a href="{{ url('discount') }}"><img src="{{ asset('images/discounts.PNG') }}" class="d-block w-100"/> </a>
                        </div>

                        <div class="row mt-5">
                            <div class="col-12">
                                <h3>Cele mai noi produse</h3>
                            </div>
                            {% for product in productsNewest %}
                                {{ include ('default/product/productCard.html.twig') }}
                            {% endfor %}
                        </div>

                        <div class="row mt-5">
                            <div class="col-12">
                                <h3>Cele mai noi lansete de feeder</h3>
                            </div>

                            {% for product in productsRods %}
                                {{ include ('default/product/productCard.html.twig') }}
                            {% endfor %}

                        </div>


                        <div class="row mt-5">
                            <div class="col-12">
                                <h3>Cele mai noi mulinete de feeder</h3>
                            </div>

                            {% for product in productsReels %}
                                {{ include ('default/product/productCard.html.twig') }}
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/product.html.twig
{% extends 'base.html.twig' %}

{% block title %} Product{% endblock %}

{% block body %}
    <div class="container ">
        <div class="container mt-5">
            <div class="row">
                <div class="col-12 mt-5">
                    <h1>{{ product.name }}</h1>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12">
                    <div class="row row mt-5 ">
                        <div class="col-5 border border-success ">
                            <img class="card-img-top mt-5" src="{{ asset('images/' ~ product.images.first) }}"
                                 alt="{{ product.name }}">
                        </div>
                        <div class="col-4">
                            <div>
                                <span>
                                    Vandut de: <a
                                            href="{{ url('vendor', {'vendor':product.vendor.id}) }}">{{ product.vendor.name }}</a>
                                </span>
                            </div>
                            <div class="mt-2">
                                Garantie comerciala: <strong>24 luni</strong>
                            </div>
                            <div class="text-center mt-4" >
                                <h5>Rezerva in magazin si livram astazi</h5>
                            </div>
                        </div>
                        <div class="col-3">
                            <div>
                                <h6><s>{{ product.price |number_format(2, '.', '.') }}</s> Lei (-{{ product.discount }}
                                    %)</h6>
                                <h3 style="color: red">{{ product.finalPrice |number_format(2, '.', '.') }} Lei</h3>
                            </div>
                            <a href="{{ url('cart_add', {'product':product.id}) }}" class="btn btn-success w-100 mt-4">Adauga in Cos</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row row mt-5">
            <div class="col-12">
                <h2>Descriere</h2>
            </div>
            <div class="col-12">
                <p>{{ product.description }}</p>
            </div>
        </div>
    </div>

{% endblock %}

templates/default/userPage.html.twig
{% extends 'base.html.twig' %}

{% block title %}User Page{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5 mb-2">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Profilul tau</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">4</th>
                        <td><a href="{{ url('crud_user_profile_index') }}">Add/Delete/Edit User </a></td>
                    </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}

templates/default/vendor.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vendors{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12"><h2> {{ vendor.name }} </h2>  </div>

            {% for product in vendor.getProducts() %}
                {{ include ('default/product/productCard.html.twig') }}
            {% endfor %}

        </div>
    </div>
{% endblock %}